# Generated by Django 2.1.4 on 2018-12-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181209_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=50)),
                ('positive', models.IntegerField(null=0)),
                ('negative', models.IntegerField(null=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
        migrations.DeleteModel(
            name='Emotions',
        ),
    ]
